### PR TITLE
	Adding Story About TV Network Deal for Conf or Team

### PR DESCRIPTION
**Pull request by destilla**
IMPORTANT: If this story triggers, there's a 20% chance that if it hasn't already, a conference will be granted a TV deal, which gives every team a prestige bonus. I set the bonus to be 5, unless they had already gotten a team TV deal, in which case the bonus is 1. saveBless gets no additional prestige. If the conference already has a TV Deal, this story is skipped and a different one is printed in week 0.

I'd like your feedback on that for balance purposes or if we should just remove the prestige bonus all together.

---

Mechanics: If this story is triggered, a switch statement is performed to figure out what the name of the conference tv network will be. The total number of individual team tv deals that have been reached (aka the number of times this story has triggered to run the generic individual team tv network (think Longhorn Network) for teams within the conference), and their names are added to a string array.

If there are no team deals, and no conf deal, there's a 20% chance the conf tv network is formed.

If there are team deals and no conf deal, there's a 20% chance the conf tv network is formed and the story printed references having to come to an agreement with the teams that already had their own channel.

If there is no team deal for saveBless and no conf deal, and the 20% chance fails, saveBless gets their own network (special stories exist for HOL and ULA cause that's Hollywood and LA and well...TV is what they do)

Otherwise, the for loop is tried again for a different story.

### CODE REVIEW

**Comment by destilla** [comment]
Screenshots (I've cleaned up some of the typos and grammatical errors since these were taken):

School TV deal: http://imgur.com/OJAeUeA (for non HOL or ULA team)

School TV deal for HOL or ULA: http://imgur.com/VvdEjmN

Conference TV deal with no existing team deals: http://imgur.com/C5tdIxx

Conference TV deal with existing Team Deals: http://imgur.com/JgyiRZG (I swear the fact that it was "Austin" being difficult was random chance)

**Comment by jonesguy14** [comment]
This is dope, I think the prestige bonus is fine since it happens fairly rarely. 

One thing that needs to be changed before I merge is just related to backwards compatibility. Right now you store teamTVdeal and confTVdeal in the save file at slots 20 and 21 in the CSV team line, but what if the user tries to load an old save of the game? It would probably throw an exception for the array being out of bounds since the TVdeal stuff wasn't saved on that file. That's why I have all those checks about if the teamInfo.length >= some number, so that it only gets stuff from the save file that actually exists.

So just put some checks for backwards compatibility and then we should be good to go. Love the story though, adds more variety which is cool.

**Comment by destilla** [comment]
You know, I figured there was some reason you had all those checks in the
team constructor, that's actually a really simple way of handling backwards
compatibility. I'm going to a concert tonight but when I get a chance
tomorrow I'll fix it and make a post letting you know.

Thanks for the feedback! I'm really happy with how these scenarios turned
out.

**Comment by destilla** [comment]
Alright, added backwards compatibility with 7072691

I think I did it right; I just based it on what you did with the other backwards compatibility checks and added two to the number that was being checked, because I added two variables.

Sorry for not catching that on my own, like I said, I knew there was some reason those if statements were there, but for whatever reason I couldn't figure out why.

**Comment by jonesguy14** [comment]
Perfect! I'll probably put the new updates on the Play Store soon after I add some names.

**Pull request merged**
